services:
  mongo:
    container_name: BK_BACKUP_MONGODB
    image: mongo:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app/
    logging:
      options:
        max-size: "1m"
