[tool.skjold]
sources = ["pyup"]                      # Sources to check against.
report_only = false                     # Report only, always exit with zero.
report_format = 'cli'                   # Output findings as `json`. Default is 'cli'.
cache_dir = '.skjold_cache'             # Cache location (default: `~/.skjold/cache`).
cache_expires = 86400                   # Cache max. age.
ignore_file = '.skjoldignore'           # Ignorefile location (default `.skjoldignore`).
verbose = true

[tool.flake8]
max-line-length = 100                   # Maximum line length for Flake8 to allow.
max-complexity = 10                     # Maximum McCabe complexity for functions.
per-file-ignores = "__init__.py:F401"   # Per-file ignore rules for Flake8.

[tool.pytest.ini_options]
addopts = [
    "--cov=./main/api", # Measure coverage of the `api` directory.
    "--cov-report=term-missing", # Show coverage report in the terminal.
    "--cov-report=html", # Generate an HTML coverage report.
]
filterwarnings = [
    "ignore:Deprecated call to `pkg_resources\\.declare_namespace\\('.*'\\):DeprecationWarning",
    "ignore::DeprecationWarning:google.rpc",
]
